### ISSUE TITLE
[Question] Infiniband support?

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1015]
Hello,

Asiri from G-Research here.

Just checking if there's a version of Java/C (preferably both) media drivers that supports Infiniband?

Failing that, is there any support for Mellanox extras (zero-copy) API in any of the Java/C media drivers? (again, preferably both)

Background is that we're trialing 100G networking and want to explore the landscape available to us. As Aeron is quite central to our stack, we want to make sure we pick a technology that is compatible with it (and will continue to be supported).

Many thanks!

**Comment by tmontgomery** [comment]
Hi Asiri.

Nothing out of the box for Infiniband or Mellanox. But it could be looked at. We do have an early ef_vi binding set for the native driver that could be leveraged.

**Comment by mjpt777** [comment]
Java cannot support anything other than the BSD sockets API without adding native code. C driver is the route to supporting other transports.

**Comment by asirir** [comment]
Thanks both!

We're interested in both Windows and Linux networking - but I think those extra APIs (ef_vi / zero-copy / extras) are only available for Linux (windows kernel-bypass options are limited).

@tmontgomery where / how can I get access to the latest version of those ef_vi bindings? (We already have SolarFlare equipment)

In our native tools (non-aeron), we use SolarFlare zero-copy API (which is sort of one abstraction level up on the ef_vi interface). There we have seen ~20-30% improvements in latency. Would be interesting to see how Aeron performs with the ef_vi interface.

If the ef_vi bindings come in source form, I maybe able to swap that for the Mellanox API with some effort. This would be ideal.

Cheers,

**Comment by tmontgomery** [comment]
@asirir send email to the support email address and one of us will send you the bindings from the last release compiled for Linux.

**Comment by asirir** [comment]
Closing - I have received the vfs bindings.
