### ISSUE TITLE
Identifying aeron subscriptions - custom tags

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1192]
Hello,

We'd like to use a custom tag like ```<channel-spec>?gr_application_id=blahblah``` when subscribing to an aeron publication. The motivation is that at the source (sender AMD) we can identify what process (application) is currently connected to a given publication.

The problem I have at the moment is that this tag seems to be getting truncated somewhere. At the sender AMD when I examine the stats (by peeking into the CnC file via aeron-client API), I can only see ```bla``` in for the above example.

Are there any limitations to using tags this way?

Many thanks.

/ Asiri

**Comment by mjpt777** [comment]
You can consider using the `alias` param as that is what it was intended for.

Regarding truncation. What is the total length of your URI and what version of Aeron are you using? The labels have a limit and will truncate at that limit.

**Comment by asirir** [comment]
Hi Martin,

Thanks for the info. I've switched to using ```alias```.

Our aeron-client version (C) is: ```1.23.1```
Media driver version: ```1.29.0```

At the moment our channel spec looks like: ```aeron-spy:aeron:udp?endpoint=239.54.40.1:20541|interface=10.10.54.0/24|alias=qa.lse.gtp.qa.listener.1of1.decoder.1of1.snapshotter,40100```

Admittedly, the ```alias``` (formerly ```gr_application_id```) could be a bit shorter - but it would be good to know the limits of these so we can come up with some scheme to shorten it. Is there any documentation covering these aspects?

Many thanks.

/ Asiri

**Comment by asirir** [comment]
Forgot to mention: with the above channel spec I get the alias truncated to ```qa.lse.gtp.qa.l```.

Thanks.

**Comment by mjpt777** [comment]
@asirir Here is the counters layout definition. https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/status/CountersReader.java#L60

**Comment by asirir** [comment]
Hi Martin,

Thanks - so the key buffer is limited to 112 bytes (which includes stream id, session id and channel). That would explain the truncation of the channel string.

Interestingly, it looks like ```label``` field can accommodate the entire channel string. For the above example (for a given snapshot) I can see something like: ```sub-pos: 219 901255607 40100 aeron-spy:aeron:udp?endpoint=239.54.40.1:20541|interface=10.10.54.0/24|alias=qa.lse.gtp.qa.listener.1of1.decoder.1of1.snapshotter @1196367008```

I can easily extract the full alias from this label instead of looking in the key buffer. Would that be a sensible thing to do?

Thanks.

/ Asiri

**Comment by mjpt777** [comment]
Yes, these layouts are reliable.

**Comment by asirir** [comment]
Cool. Thanks for the help.

Closing.
