### ISSUE TITLE
Question about counter labels and aliases

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1203]
Hello,

This is a follow-up from https://github.com/G-Research/aeron/issues/1192.

We tried appending the ```alias``` parameter to our subscription requests and publication requests. This worked OK but there is a small issue when reading counter labels corresponding to subscriptions in some cases.

When reading publisher counters we get labels like:
`pub_pos: ... <channel>|alias=<publisher_alias> @...`
This allows us to identify the publisher easily - no ambiguity.

When reading subscription counters we get labels like:
`sub_pos: ... <channel>|alias=<publisher_alias>|alias=<subscriber_alias> @...`
This is still OK if both the publisher and the subscriber have registered with an alias - the subscriber alias appear last.

The difficulty we're having atm is, if only one of the subscriber/publisher is using an alias (it's difficult for us to demand all subscriptions and publications provide an ```alias``` when registering), in the second case (reading a subscription counter), we cannot tell if the alias parameter is coming from the subscriber or the publisher.

We experimented with using two separate params: ```pub_alias``` for publishers and ```sub_alias``` for subscribers. This seems to work, but want to check with you if this is OK (specially because ```alias``` is the recommended way)? Perhaps there is a way to use ```alias``` still and be able to distinguish the source (publisher or subscriber) in all cases?

Our aeron-client version (C) is: 1.23.1
Media driver version: 1.29.0

Many thanks.

/ Asiri

**Comment by mjpt777** [comment]
I don't understand how you think you have publisher alias on the subscription counter. Can you further explain?

**Comment by asirir** [comment]
Hi Martin.

My counters scanner looks something like this:
` 
       counters.forEach([&](int32_t counter_id, int32_t type_id, const aeron::AtomicBuffer &key_buffer, const std::string &label)
        {
            switch (type_id)
            {
                case PUBLISHER_POSITION_TYPE_ID:
                    Log.info() << "Publisher position counter label: " << label;
                    return;
                case SUBSCRIBER_POSITION_TYPE_ID:
                    Log.info() << "Subscribe position counter label: " << label;
                    return;
                default:
                    // Ignore other counters
                    return;
            }
    }
`
The label printed for the publisher only has one ```alias``` set - but the one printed for the subscriber has two of them in the label. It looks like the subscriber's alias and the corresponding publisher's alias (the publication to which this subscriber is subscribed to) both appear in the label for the ```SUBSCRIBER_POSITION_TYPE_ID``` counter.

Let me revert the hack above (```pub_alias``` and ```sub_alias```) and double check that this is correct.

Thanks.

/ Asiri

**Comment by mjpt777** [comment]
It looks like your subscribers are adding the alias to the publication URI. This is not something Aeron would be doing.

**Comment by asirir** [comment]
Sigh, you are absolutely right - totally missed that. Sorry for the noise.

/ Asiri

**Comment by mjpt777** [comment]
No worries. :-)
