### ISSUE TITLE
Question about counter Ids

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1213]
Hello,

We're attempting build insight into the status of various publications / subscriptions within the AMD. For this we are reading the various counters available. For each counter, we parse the channel, alias, stream_id, value etc. so that we can build a picture of the AMD state.

I was wondering if we can avoid parsing these values for each snapshot of the counters by utilizing the ```counter_id``` field - if this value is "stable", in the sense that a particular counter will always have the same ```counter_id``` for a given AMD process - then I can simply use a lookup table to access the stored state (in my program) to access previously parsed values.

Looking at: https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/status/CountersReader.java#L329
It seems like ```counterId``` is sort of an offset into a counter.

It feels like this should be stable for a given AMD process. Is this a fair assumption?

Many thanks.

/ Asiri

**Comment by mjpt777** [comment]
This assumption is reasonable. This was one of the reasons we added the registration id to each counter to be able to detect if a counter has been reused. 

If you read the counter value then read the registration id after and if still what you expect then the value is valid. The reading of value and registration id via the API are memory ordered atomic operations to do this safely. You will want to update to benefit from this. This week we will be doing a new Aeron release that will have your archive changes.

**Comment by asirir** [comment]
Cool! :)

Thanks Martin!
