### ISSUE TITLE
Counters for remote subscriptions / receivers?

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1217]
Hello,

We use aeron to deliver messages across the network (UDP), where we have a publisher + sender AMD (send_amd_a) on box A and many subscribers + receiver AMD (recv_amd_b) on box B.

When examining counters on ```send_amd_a``` I cannot see any counters for the subscribers on the remote box there (this maybe expected). Moreover, I cannot see any counters corresponding to the receiver ```recv_amd_b``` either - my expectation was that the remote receiver AMD would show up on to the sender AMD as a single subscription in the counters.

Is this incorrect?

I'm hoping I'd be able to view all the remote receivers (remote subscribers would be perfect - but that's probably too much of an ask) currently subscribed to my publication on the sender AMD.

Many thanks.

/ Asiri

**Comment by tmontgomery** [comment]
Counters are only local to the local MD. So, in the example you have `send_amd_a` will only have Publication counters (pub-lmt, snd-lmt, snd-pos, etc.) for the publication as that is the only things local to that MD. And `recv_amd_b` will only have Subscription counters (sub-pos, rcv-hwm, rcv-pos, etc.) for the subscriptions as that is the only things local to that MD.

We have discussed before the concept of distributed counters, but have not had a sponsor for them as of yet.

**Comment by asirir** [comment]
Hi Todd,

Thanks for the explanation. I'll have a chat with our folks.

/ Asiri
