### ISSUE TITLE
Extending an aeron-archive recording

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1277]
Hello,

We have a requirement where when a service is restarted, it should extend its previous recording (append the new data to it) rather than start a fresh recording (the latter is our current behavior).

I've tried to implement this following the API but it looks like the recording is not being appended to - all the calls succeed but the publication of the restarted service gets back-pressured soon after. Also, checking the archive-catalogue, I cannot see the recording being appended to.

This is the state of the recording when the service is restarting:
```
...
{"Name": "CatalogHeader", "sbeTemplateId": 20, "version": 228, "entryLength": 1}
{"Name": "RecordingDescriptor", "sbeTemplateId": 22, "controlSessionId": 0, "correlationId": 0, "recordingId": 3, "startTimestamp": 1614785608313, "stopTimestamp": 1614785770549, "startPosition": 0, "stopPosition": 4636017664, "initialTermId": -1099179382, "segmentFileLength": 536870912, "termBufferLength": 536870912, "mtuLength": 1408, "sessionId": -1908601588, "streamId": 40001, "strippedChannel": "aeron:ipc", "originalChannel": "aeron:ipc?feed_date=20210303|fleet_file=lse_gtp_direct_20210303.dsg|feed_id=LSE.GTP200.GR.LS.QA2|term-length=536870912", "sourceIdentity": "aeron:ipc"}
```
I'm calling the following API for extending this recording: https://github.com/real-logic/aeron/blob/9feda0b215c23891e0d5111448d58ed0b7c26464/aeron-archive/src/main/cpp/client/AeronArchive.h#L505

I'm also using the relevant ```ChannelUriStringBuilder::initialPosition()``` function for setting up the initial position: https://github.com/real-logic/aeron/blob/9feda0b215c23891e0d5111448d58ed0b7c26464/aeron-client/src/main/cpp/ChannelUriStringBuilder.h#L298

In the case of the above recording, I'd be passing ```(4636017664, -1099179382, 536870912)``` to this function as I want the recording to be extended with the new data from the old stop-position.

My logs also indicate that we get a subscription-id for the new (appending) recording:
```
...
2021-03-03T16:14:24.923646Z INFO [26165] LSE.GTP200.GR.LS.QA2.LISTENER/gr_library::aeron::archive::aeron_archive : Starting to append recording [3] from position [4636017664] for channel: [aeron:ipc?term-length=536870912|init-term-id=-1099179382|term-id=-1099179374|term-offset=341050368,40001] with subscription id: 130
```
(The channel string here is the output of the ```ChannelUriStringBuilder::build()``` method - which is what I pass onto the ```AeronArchive::extendRecording()``` function).

The archive catalogue (listed above) remain unchanged even though the data is being pushed to the publication (I would expect the ```stopPosition``` to read ```-1``` as soon as the appending started).

Am I doing something wrong here? Perhaps I have misunderstood the API?

My aeron-client API verison is: ```1.32.0``` (latest)
My AMD version is: ```1.29.0```

Many thanks.

/ Asiri

**Comment by tmontgomery** [comment]
> (The channel string here is the output of the ChannelUriStringBuilder::build() method - which is what I pass onto the AeronArchive::extendRecording() function).

The channel URI with the `initialPosition` is for the publication and not the `extendRecording`. You might look at https://github.com/real-logic/aeron/blob/master/aeron-system-tests/src/test/java/io/aeron/archive/ExtendRecordingTest.java#L193

The extending publication needs to begin at the position of the

**Comment by asirir** [comment]
Thanks for the quick reply - I see my mistake now :)

Closing.
