### ISSUE TITLE
Upgrading Java version

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1326]
Hello,

We recently got a notification (I believe through RealLogic) that we should upgrade our Java version to 1.8.0_282 (or above). Just want to check if there is a recommended Java vendor? We currently use OpenJDK without any issues (on both Windows and Linux). Switching to Oracle would be expensive as the version above requires a commercial license.

Many thanks.

/ Asiri

**Comment by mjpt777** [comment]
Any OpenJDK version is fine. We regularly test with Azul Zulu. They have a free version and can offer commercial support.

**Comment by asirir** [comment]
Thanks Martin.
