### ISSUE TITLE
Automatic cleanup of Aeron Archive Recordings

### ISSUE THREAD

**Issue by rahj0** [G-Research/aeron#1479]
Hi,

We have a use case where we only restart the media driver and Aeron Archive once a week. We have tooling that cleans up Aeron archive recordings when we restart but in this case that's not often enough. We are therefore looking into how to do this better.

Is there anything we can use for the cleanup or some best practices we should follow? 

Alternatively would it possible to add an argument for the Aeron archiver to delete old recordings, e.g. recordings more than x days old?

Many Thanks,
Rasmus

**Comment by mjpt777** [comment]
Hi Rasmus,

Within Archive we cannot tell if a recording is no longer needed so we take the safe approach and do not delete recordings or segments unless instructed to do so.

Users of Archive typically run a job on a schedule to see what recordings or segments can be purged when no longer needed. This can be as simple as a job that checks file timestamps or the recording start and stop timestamps. The Archive client has an API to purge what is required. It can also help to add an `alias`  to the channel URI of a recording to signify its purpose and thus make identification of specific recordings easier. 

A possible feature we could add with your support time would be an operation to purge recordings with a stopped time older than a provided value. Is this what you had in mind?

Regards,
Martin...

**Comment by rahj0** [comment]
Hi Martin,

Thanks for your reply.

I think we will try with a custom job as you describe for now. The feature you suggest probably won't be needed then.

Many thanks,
Rasmus
